# =============================================================================
# Backup Labels Referenz
# =============================================================================
# Füge diese Labels zu deinen Datenbank-Containern hinzu.
# Der db-backup Container liest diese Labels automatisch.
# =============================================================================

# =============================================================================
# POSTGRESQL
# =============================================================================
# Für PostgreSQL Container (postgres, timescaledb, etc.)

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-main
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: myapp
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      # === BACKUP KONFIGURATION ===
      - "db-backup.enable=true"
      - "db-backup.type=postgres"
      - "db-backup.schedule=0 2 * * *"        # Täglich um 02:00
      - "db-backup.database=myapp"            # Oder "all" für alle DBs
      - "db-backup.user=myuser"
      - "db-backup.password=${POSTGRES_PASSWORD}"
      - "db-backup.retention=14"              # 14 Tage behalten
      - "db-backup.compression=gzip"
      # Optional: Custom Host/Port falls nicht Container-Name
      # - "db-backup.host=postgres-main"
      # - "db-backup.port=5432"
      # Optional: Extra pg_dump Argumente
      # - "db-backup.extra-args=--no-owner --no-acl"


# =============================================================================
# MYSQL
# =============================================================================
# Für MySQL Container

services:
  mysql:
    image: mysql:8
    container_name: mysql-main
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    labels:
      - "db-backup.enable=true"
      - "db-backup.type=mysql"
      - "db-backup.schedule=0 */6 * * *"      # Alle 6 Stunden
      - "db-backup.database=wordpress"
      - "db-backup.user=root"
      - "db-backup.password=${MYSQL_ROOT_PASSWORD}"
      - "db-backup.retention=7"
      - "db-backup.compression=gzip"
      # Empfohlene Extra-Args für konsistente Backups
      - "db-backup.extra-args=--single-transaction --quick --lock-tables=false"


# =============================================================================
# MARIADB
# =============================================================================
# Für MariaDB Container (identisch zu MySQL)

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-main
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: ncuser
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    labels:
      - "db-backup.enable=true"
      - "db-backup.type=mariadb"
      - "db-backup.schedule=30 3 * * *"       # Täglich um 03:30
      - "db-backup.database=all"              # Alle Datenbanken
      - "db-backup.user=root"
      - "db-backup.password=${MARIADB_ROOT_PASSWORD}"
      - "db-backup.retention=30"
      - "db-backup.compression=zstd"          # Bessere Kompression
      - "db-backup.extra-args=--single-transaction"


# =============================================================================
# MONGODB
# =============================================================================
# Für MongoDB Container

services:
  mongodb:
    image: mongo:7
    container_name: mongodb-main
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    labels:
      - "db-backup.enable=true"
      - "db-backup.type=mongodb"
      - "db-backup.schedule=0 4 * * 0"        # Sonntags um 04:00
      - "db-backup.database=all"
      - "db-backup.user=admin"
      - "db-backup.password=${MONGO_PASSWORD}"
      - "db-backup.retention=28"              # 4 Wochen
      - "db-backup.compression=gzip"
      # Optional: Nur bestimmte DB
      # - "db-backup.database=myapp"


# =============================================================================
# REDIS
# =============================================================================
# Für Redis Container

services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis-data:/data
    labels:
      - "db-backup.enable=true"
      - "db-backup.type=redis"
      - "db-backup.schedule=0 */12 * * *"     # Alle 12 Stunden
      - "db-backup.password=${REDIS_PASSWORD}"
      - "db-backup.retention=3"               # Nur 3 Tage
      - "db-backup.compression=gzip"


# =============================================================================
# VALKEY (Redis Fork)
# =============================================================================
# Für Valkey Container (Redis-kompatibel)

services:
  valkey:
    image: valkey/valkey:8-alpine
    container_name: valkey-cache
    command: valkey-server --requirepass ${VALKEY_PASSWORD}
    volumes:
      - valkey-data:/data
    labels:
      - "db-backup.enable=true"
      - "db-backup.type=redis"                # Nutzt redis-cli
      - "db-backup.schedule=0 5 * * *"
      - "db-backup.password=${VALKEY_PASSWORD}"
      - "db-backup.retention=7"


# =============================================================================
# SQLITE (z.B. für Authelia, Vaultwarden)
# =============================================================================
# Für Container die SQLite nutzen

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - vaultwarden-data:/data
    labels:
      - "db-backup.enable=true"
      - "db-backup.type=sqlite"
      - "db-backup.schedule=0 1 * * *"        # Täglich um 01:00
      - "db-backup.database=/data/db.sqlite3" # Pfad zur DB im Container
      - "db-backup.retention=30"
      - "db-backup.compression=gzip"


# =============================================================================
# CRON SCHEDULE REFERENZ
# =============================================================================
#
# Format: Minute Stunde Tag Monat Wochentag
#
# Beispiele:
#   0 2 * * *      = Täglich um 02:00
#   0 */6 * * *    = Alle 6 Stunden
#   30 3 * * *     = Täglich um 03:30
#   0 4 * * 0      = Sonntags um 04:00
#   0 0 1 * *      = Am 1. jeden Monats um Mitternacht
#   0 */4 * * 1-5  = Alle 4 Stunden an Werktagen
#   */15 * * * *   = Alle 15 Minuten (nur für Tests!)
#
# =============================================================================
# LABEL REFERENZ
# =============================================================================
#
# | Label                    | Pflicht | Default      | Beschreibung                    |
# |--------------------------|---------|--------------|----------------------------------|
# | db-backup.enable         | ✅      | false        | Backup aktivieren               |
# | db-backup.type           | ✅      | -            | postgres/mysql/mariadb/mongodb/redis/sqlite |
# | db-backup.schedule       | ❌      | 0 2 * * *    | Cron Schedule                   |
# | db-backup.database       | ❌      | all          | Datenbankname oder "all"        |
# | db-backup.user           | ❌      | -            | DB Benutzername                 |
# | db-backup.password       | ❌      | -            | DB Passwort                     |
# | db-backup.password-file  | ❌      | -            | Pfad zu Passwort-Datei          |
# | db-backup.host           | ❌      | Container    | DB Host                         |
# | db-backup.port           | ❌      | Auto         | DB Port                         |
# | db-backup.retention      | ❌      | 7            | Tage behalten                   |
# | db-backup.compression    | ❌      | gzip         | gzip/zstd/none                  |
# | db-backup.extra-args     | ❌      | -            | Extra Dump-Argumente            |
#
# =============================================================================
